apps/aluno/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.core import views


app_name = 'aluno'

from . import views

urlpatterns = [

    #adicionando a view do core
    path('',views.HomeView.as_view(),name='home'),
    path('novo/',views.AddAluno,name='add_aluno'),
    path('lista/',views.lista_Alunos,name='lista_alunos'),
    path('editar/<int:id_aluno>/',views.edit_aluno,name='edit_aluno'),
    path('delete/<int:id_aluno>/',views.deleteAluno,name='delete_aluno'),
    path('usuario/', include('usuario.urls', namespace='usuario')),
   
   
  
]

campus/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.core import views
from apps.aluno import views


urlpatterns = [

    #adicionando a view do core
    path('admin/', admin.site.urls),
    path('aluno/', include('aluno.urls', namespace='aluno')),
    path('professor/', include('professor.urls', namespace='professor')),
    path('usuario/', include('usuario.urls', namespace='usuario')),
    path('', include('core.urls')),
    
    

]

apps/aluno/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Aluno(models.Model):
    nome = models.CharField(max_length=100,help_text='Nome do Aluno')
    cpf = models.CharField(max_length=12,help_text='CPF do Aluno',blank=False,default='')
    email = models.CharField(max_length=100,help_text='e-mail',default='')
    data_nasc = models.DateField('Data de Nascimento',auto_now=False,auto_now_add=False,blank=True,default='')



class Meta:
    ordering=['-id']

#exibe o nome do aluno no admin no lugar no nome do objeto
def __str__(self):
    return self.nome

apps/aluno/forms.py
from django import forms
from aluno.models import Aluno


class AlunoForm(forms.ModelForm):
    class Meta:
        model = Aluno
        #fields = ['nome','cpf','email','data_nasc','user']
        fields = '__all__'
        

apps/aluno/views.py
from django.shortcuts import render,redirect, get_list_or_404,get_object_or_404
from aluno.models  import Aluno
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from aluno.forms import AlunoForm
from django.views.generic import TemplateView,CreateView,ListView



# def novoAluno(request):
#    template_name = 'aluno/add_aluno.html'
#    context = {}
#    form = AlunoForm()
#    context['form'] = form
#    return render(request,template_name,context)

class HomeView(TemplateView):
   template_name = 'aluno/lista_alunos.html'
   

# class AddAlunoView(CreateView):
#       template_name = 'aluno/add_aluno.html'
#       model = Aluno
#       form_class = AlunoForm
#       messages.success( "Usuário salvo com sucesso!")
#       success_url = 'aluno/add_aluno.html' 
    



# @login_required(login_url='usuario:user_login')
# class ListAlunosView(ListView):
#    model =Aluno
#    template_name = 'aluno/lista_alunos.html'
#    context_object_name = 'alunos'
#    paginate_by = 6

#    def get_queryset(self):
#        return Aluno.objects.all().order_by('-id')
@login_required(login_url='usuario:user_login')
def lista_Alunos(request):
    context = {}
    template_name = 'aluno/lista_alunos.html'
    alunos = Aluno.objects.all().order_by('-id')
    context = {'alunos':alunos} 
    return render(request,template_name,context)


@login_required(login_url='usuario:user_login')
def deleteAluno(request, id_aluno):
    aluno = Aluno.objects.get(id=id_aluno)
    aluno.delete()
    return redirect('aluno:lista_alunos')

@login_required(login_url='usuario:user_login')
def edit_aluno(request, id_aluno):
    template_name = 'aluno/add_aluno.html'
    context = {}
    aluno = get_object_or_404(Aluno, pk=id_aluno)
    if request.method == 'POST':
        form = AlunoForm(request.POST, instance=aluno)
        if form.is_valid():
            form.save()
            return redirect('aluno:lista_alunos')
    form = AlunoForm(instance=aluno)
    context['form'] = form
    return render(request, template_name, context)

# Create your views here.


# def home(request):
#     return render(request,'base.html',{})


@login_required(login_url='usuario:user_login')
def AddAluno(request):
    template_name = 'aluno/add_aluno.html'
    context = {}
    if request.method == 'POST':
        form = AlunoForm(request.POST)
        if form.is_valid():
            # f = form.save(commit=False)
            form.save()
            messages.success(request, "Usuário salvo com sucesso!")
        else:
            messages.error(request, "Erro ao salvar dados!")
    form = AlunoForm()
    context['form'] = form
    return render(request,template_name,context)



  


# def lista_Alunos(request):
#     template_name = 'aluno/lista_alunos.html'
#     alunos = Aluno.objects.all().reverse()
#     context = { 'alunos':alunos  }
#     print(context)
#     return render(request,template_name,context)


templates/aluno/add_aluno.html
{% extends 'base.html' %}

{%load widget_tweaks%}

{% block title %}
{{block.super}} - Cadastro de Alunos
{% endblock title %}

{% block body %}




<div class="container">
  

    <div class="row">
        <div class="input-field col-6">

            <div class="form-group ">
                <h3>Novo Aluno</h3>
            </div>
            {% include 'partials/messages.html' %}
            <form action="." method="POST" autocomplete="off">
                {% csrf_token %}
                <div class="form-group col">
                    <label for="{{ form.name.id_for_label }}">Nome</label>
                    {{ form.nome|add_class:"form-control"|attr:"autofocus" }}
                </div>
        
                <div class="form-group col">
                    <label for="{{ form.cpf.id_for_label }}">CPF</label>
                    {{ form.cpf|add_class:"form-control" |attr:"autofocus"}}
                </div>
                <div class="form-group col">
                    <label for="{{ form.email.id_for_label }}">E-Mail</label>
                    {{ form.email|add_class:"form-control" |attr:"autofocus"}}
                </div>

                <div class="form-group col-4">
                    <label for="form.data_nasc.id_for_label">Data de Nascimento:</label>
                    {{ form.data_nasc|add_class:"form-control" |attr:"autofocus"}}

                </div>

                <div class="form-group col-6">
                    
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-primary">Limpar</button>
                   
                   
                </div>

        </div>



        </form>
    </div>
</div>




</div>

{% endblock body%}

templates/aluno/lista_alunos.html
{% extends 'base.html' %}

{%load widget_tweaks%}

{% block title %}
{{block.super}} - Lista de Alunos
{% endblock title %}

{% block body %}


<h2>Lista de Alunos</h2>

<div class="row">
    <div class="col-md-12">
        {% include 'partials/messages.html' %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Id</th>
                    <th scope="col">Nome</th>
                    <th scope="col">CPF</th>
                    <th scope="col">User</th>
                    <th scope="col">E-mail</th>
                    
                </tr>
            </thead>
            <tbody>
                {%for aluno in alunos %}
                <tr>
                    <th scope="col">#</td>
                    <td scope="col">{{aluno.id}}</td>
                    <td scope="col">{{aluno.nome}}</td>
                    <td scope="col">{{aluno.cpf}}</td>
                    <td scope="col">{{aluno.email}}</td>
                    <td>
                        <a href="{% url 'aluno:edit_aluno' aluno.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'aluno:delete_aluno' aluno.id %}" class="btn btn-danger btn-sm confirm-delete" id="deleteButton-{{ aluno.id }}">Excluir</a>
                    </td>
                </tr>
           
                {%endfor%}  

            </tbody>
        </table>
    </div>
</div>

{% endblock body %}